name: sama_net_messaging_app_mobile
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.4.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  permission_handler: ^11.0.1
  dio: ^5.3.2
  path: ^1.8.3
  path_provider: ^2.1.1
  mime: ^1.0.4
  video_player: ^2.7.2
  cached_network_image: ^3.3.0
  signalr_core: ^1.1.1
  flutter_local_notifications: ^17.2.3
  open_filex: ^4.5.0

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/styles/style_messaging.json

